from pathlib import Path

gemini_py = [
    'import os',
    'import streamlit as st',
    'from dotenv import load_dotenv',
    'from google import genai',
    '',
    'load_dotenv()',
    '',
    'API_KEY = os.getenv("GEMINI_API_KEY")',
    '',
    'st.set_page_config(',
    '    page_title="Simple Gemini Chatbot",',
    '    page_icon="🤖"',
    ')',
    '',
    'st.title("🤖 Simple Gemini AI Chatbot")',
    'st.write("Ask me anything and I will try to help!")',
    '',
    'if not API_KEY:',
    '    st.error("GEMINI_API_KEY is not configured.")',
    '    st.info("Create a .env file and add your Gemini API key.")',
    '    st.stop()',
    '',
    'client = genai.Client(api_key=API_KEY)',
    '',
    'if "messages" not in st.session_state:',
    '    st.session_state.messages = []',
    '',
    'for message in st.session_state.messages:',
    '    with st.chat_message(message["role"]):',
    '        st.markdown(message["content"])',
    '',
    'prompt = st.chat_input("Type your message...")',
    '',
    'if prompt:',
    '    st.session_state.messages.append({',
    '        "role": "user",',
    '        "content": prompt',
    '    })',
    '',
    '    with st.chat_message("user"):',
    '        st.markdown(prompt)',
    '',
    '    try:',
    '        conversation = ""',
    '',
    '        for message in st.session_state.messages:',
    '            conversation += message["role"].capitalize() + ": " + message["content"] + "\\n"',
    '',
    '        response = client.models.generate_content(',
    '            model="gemini-2.5-flash",',
    '            contents=conversation',
    '        )',
    '',
    '        answer = response.text',
    '',
    '    except Exception as e:',
    '        answer = f"Error: {e}"',
    '',
    '    st.session_state.messages.append({',
    '        "role": "assistant",',
    '        "content": answer',
    '    })',
    '',
    '    with st.chat_message("assistant"):',
    '        st.markdown(answer)'
]

requirements = [
    'streamlit',
    'google-genai',
    'python-dotenv'
]

gitignore = [
    'venv/',
    '.env',
    '__pycache__/',
    '*.pyc',
    '.streamlit/secrets.toml'
]

env_example = [
    'GEMINI_API_KEY=your_gemini_api_key_here'
]

readme = [
    '# Simple Gemini AI Chatbot',
    '',
    'A simple AI chatbot built using Python, Streamlit, and the Google Gemini API.',
    '',
    '## Objective',
    '',
    'The objective of this project is to create a simple chatbot that can hold basic conversations with users through a web interface.',
    '',
    '## Features',
    '',
    '- Simple web interface',
    '- AI-generated responses',
    '- Conversation history',
    '- User and chatbot messages',
    '- Secure API key configuration',
    '',
    '## Technologies Used',
    '',
    '- Python',
    '- Streamlit',
    '- Google Gemini API',
    '- python-dotenv',
    '',
    '## Approach',
    '',
    'This project uses a Generative AI API approach.',
    '',
    'User messages are sent to the Google Gemini model through the Gemini API. The generated response is displayed in the Streamlit web interface.',
    '',
    '## Project Structure',
    '',
    '```text',
    'Simple-Chatbot/',
    '|',
    '|-- generate.py',
    '|-- gemini.py',
    '|-- requirements.txt',
    '|-- README.md',
    '|-- .gitignore',
    '|-- .env.example',
    '|-- .env',
    '`-- venv/',
    '```',
    '',
    '## Installation',
    '',
    '### 1. Create a virtual environment',
    '',
    '```bash',
    'python -m venv venv',
    '```',
    '',
    '### 2. Activate the virtual environment',
    '',
    '```bash',
    'venv\\Scripts\\activate',
    '```',
    '',
    '### 3. Install dependencies',
    '',
    '```bash',
    'pip install -r requirements.txt',
    '```',
    '',
    '### 4. Configure the Gemini API key',
    '',
    'Create a file named `.env` in the project folder.',
    '',
    'Add:',
    '',
    '```text',
    'GEMINI_API_KEY=your_gemini_api_key_here',
    '```',
    '',
    'Do not upload the `.env` file to GitHub.',
    '',
    '### 5. Run the chatbot',
    '',
    '```bash',
    'streamlit run gemini.py',
    '```',
    '',
    '## API Key Security',
    '',
    'The Gemini API key is stored in a `.env` file.',
    '',
    'The `.env` file is included in `.gitignore, so the API key is not uploaded to GitHub.',
    '',
    '## Challenges Faced',
    '',
    'One challenge was configuring the Gemini API and keeping the API key secure.',
    '',
    'This was solved by using a `.env` file and adding `.env` to `.gitignore`.',
    '',
    '## Future Improvements',
    '',
    '- Add multiple chatbot personalities',
    '- Add conversation export',
    '- Add voice input',
    '- Add voice responses',
    '- Deploy the chatbot online',
    '- Add custom knowledge using RAG',
    '',
    '## Author',
    '',
    'AMAL M K',
    '',
    'BTech Computer Science and Engineering',
    '',
    '## uLearn Task',
    '',
    'Build a Simple Chatbot',
    '',
    'Hashtag: #cl-ai-chatbot'
]

files = {
    "gemini.py": gemini_py,
    "requirements.txt": requirements,
    ".gitignore": gitignore,
    ".env.example": env_example,
    "README.md": readme
}

for filename, lines in files.items():
    Path(filename).write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("Created:", filename)

print()
print("===================================")
print("All project files created!")
print("===================================")